# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

use_frameworks!

pod 'AFNetworking','~>2.0'
pod 'MJRefresh'
pod 'SDWebImage'
pod 'FMDB'
pod 'JPush'
pod 'Reachability'
pod 'SVProgressHUD'
pod 'MJExtension'
pod 'JWT'
pod 'Masonry'
pod 'CocoaLumberjack'
pod 'TMCache'
pod 'SegmentControlLFL', '~> 1.0.0'
pod 'BlocksKit'
